# Generated by Django 3.2 on 2022-05-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_customer_reservation_table_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kysha',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
