# Generated by Django 3.2 on 2022-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrinkItem",
            fields=[
                ("drink_id", models.AutoField(primary_key=True, serialize=False)),
                ("drink_name", models.CharField(max_length=200, unique=True)),
                ("description", models.CharField(max_length=200, unique=True)),
                ("price", models.FloatField()),
                ("allergens", models.CharField(max_length=200, null=True)),
                ("on_menu", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-on_menu"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                ("dish_id", models.AutoField(primary_key=True, serialize=False)),
                ("dish_name", models.CharField(max_length=200, unique=True)),
                ("description", models.CharField(max_length=200, unique=True)),
                ("price", models.FloatField()),
                ("allergens", models.CharField(max_length=200, null=True)),
                ("on_menu", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-on_menu"],
            },
        ),
    ]
