# Generated by Django 3.2 on 2022-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20220420_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_menu_section',
            field=models.IntegerField(choices=[(0, 'Lunch'), (1, 'Dinner'), (2, 'Desserts'), (3, 'New item')], default=2),
        ),
    ]
