# Generated by Django 3.2 on 2022-05-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_alter_fooditem_food_menu_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="food_menu_section",
            field=models.IntegerField(
                choices=[(0, "Lunch"), (1, "Dinner"), (2, "Desserts"), (3, "New item")],
                default=3,
            ),
        ),
    ]
